spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  batch:
    job:
      enabled: off

jwt:
  secretKey: ${secretKey}



springdoc:
  api-docs:
    path: /api-docs

server:
  port: 9042
